server:
  port: 8080
  context.path: /auth

user:
  oauth:
    user:
      username: user
      password: pass
    clientId: client1
    clientSecret: 1234$#@!
    redirectUris: http://localhost:8081/login
    accessTokenValidity: 300
    refreshTokenValidity: 240000

logging:
  level:
    root: INFO
